title: "AI Patterns!"
description: "Sharing what I've discovered through obsessively studying the field"
remote_theme: pmarsceill/just-the-docs

url: "https://eustin.github.io"
baseurl: "/ai-patterns"

search_enabled: true
heading_anchors: true

color_scheme: dark

callouts:
  highlight:
    color: red

