title: "AI Patterns!"
description: "Sharing what I've discovered through obsessively studying the field"
theme: just-the-docs

url: "https://eustin.github.io"
baseurl: "/ai-patterns"

defaults:
  - scope:
      path: docs
      type: pages
    values:
      layout: default

search_enabled: true
heading_anchors: true

color_scheme: dark

callouts:
  highlight:
    color: red

